# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from copilot_interface/controlData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class controlData(genpy.Message):
  _md5sum = "63fc1b5d7859e5a1c46030e539babe05"
  _type = "copilot_interface/controlData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool thruster_status
bool dh_status
float32 target_depth
float32 linear_sense
float32 angular_sense
float32 vertical_sense
int32 camera"""
  __slots__ = ['thruster_status','dh_status','target_depth','linear_sense','angular_sense','vertical_sense','camera']
  _slot_types = ['bool','bool','float32','float32','float32','float32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       thruster_status,dh_status,target_depth,linear_sense,angular_sense,vertical_sense,camera

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(controlData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.thruster_status is None:
        self.thruster_status = False
      if self.dh_status is None:
        self.dh_status = False
      if self.target_depth is None:
        self.target_depth = 0.
      if self.linear_sense is None:
        self.linear_sense = 0.
      if self.angular_sense is None:
        self.angular_sense = 0.
      if self.vertical_sense is None:
        self.vertical_sense = 0.
      if self.camera is None:
        self.camera = 0
    else:
      self.thruster_status = False
      self.dh_status = False
      self.target_depth = 0.
      self.linear_sense = 0.
      self.angular_sense = 0.
      self.vertical_sense = 0.
      self.camera = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B4fi().pack(_x.thruster_status, _x.dh_status, _x.target_depth, _x.linear_sense, _x.angular_sense, _x.vertical_sense, _x.camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.thruster_status, _x.dh_status, _x.target_depth, _x.linear_sense, _x.angular_sense, _x.vertical_sense, _x.camera,) = _get_struct_2B4fi().unpack(str[start:end])
      self.thruster_status = bool(self.thruster_status)
      self.dh_status = bool(self.dh_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B4fi().pack(_x.thruster_status, _x.dh_status, _x.target_depth, _x.linear_sense, _x.angular_sense, _x.vertical_sense, _x.camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 22
      (_x.thruster_status, _x.dh_status, _x.target_depth, _x.linear_sense, _x.angular_sense, _x.vertical_sense, _x.camera,) = _get_struct_2B4fi().unpack(str[start:end])
      self.thruster_status = bool(self.thruster_status)
      self.dh_status = bool(self.dh_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B4fi = None
def _get_struct_2B4fi():
    global _struct_2B4fi
    if _struct_2B4fi is None:
        _struct_2B4fi = struct.Struct("<2B4fi")
    return _struct_2B4fi
