// Generated by gencpp from file gpio_control/gpio_statusResponse.msg
// DO NOT EDIT!


#ifndef GPIO_CONTROL_MESSAGE_GPIO_STATUSRESPONSE_H
#define GPIO_CONTROL_MESSAGE_GPIO_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gpio_control
{
template <class ContainerAllocator>
struct gpio_statusResponse_
{
  typedef gpio_statusResponse_<ContainerAllocator> Type;

  gpio_statusResponse_()
    : status(false)  {
    }
  gpio_statusResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::gpio_control::gpio_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpio_control::gpio_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gpio_statusResponse_

typedef ::gpio_control::gpio_statusResponse_<std::allocator<void> > gpio_statusResponse;

typedef boost::shared_ptr< ::gpio_control::gpio_statusResponse > gpio_statusResponsePtr;
typedef boost::shared_ptr< ::gpio_control::gpio_statusResponse const> gpio_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpio_control::gpio_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpio_control::gpio_statusResponse_<ContainerAllocator1> & lhs, const ::gpio_control::gpio_statusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpio_control::gpio_statusResponse_<ContainerAllocator1> & lhs, const ::gpio_control::gpio_statusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpio_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpio_control::gpio_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpio_control::gpio_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpio_control::gpio_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::gpio_control::gpio_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpio_control/gpio_statusResponse";
  }

  static const char* value(const ::gpio_control::gpio_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::gpio_control::gpio_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gpio_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpio_control::gpio_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpio_control::gpio_statusResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPIO_CONTROL_MESSAGE_GPIO_STATUSRESPONSE_H
