// Generated by gencpp from file gpio_control/gpio_status.msg
// DO NOT EDIT!


#ifndef GPIO_CONTROL_MESSAGE_GPIO_STATUS_H
#define GPIO_CONTROL_MESSAGE_GPIO_STATUS_H

#include <ros/service_traits.h>


#include <gpio_control/gpio_statusRequest.h>
#include <gpio_control/gpio_statusResponse.h>


namespace gpio_control
{

struct gpio_status
{

typedef gpio_statusRequest Request;
typedef gpio_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gpio_status
} // namespace gpio_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gpio_control::gpio_status > {
  static const char* value()
  {
    return "3b90914d035160dc78631aed0a7b703d";
  }

  static const char* value(const ::gpio_control::gpio_status&) { return value(); }
};

template<>
struct DataType< ::gpio_control::gpio_status > {
  static const char* value()
  {
    return "gpio_control/gpio_status";
  }

  static const char* value(const ::gpio_control::gpio_status&) { return value(); }
};


// service_traits::MD5Sum< ::gpio_control::gpio_statusRequest> should match
// service_traits::MD5Sum< ::gpio_control::gpio_status >
template<>
struct MD5Sum< ::gpio_control::gpio_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gpio_control::gpio_status >::value();
  }
  static const char* value(const ::gpio_control::gpio_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpio_control::gpio_statusRequest> should match
// service_traits::DataType< ::gpio_control::gpio_status >
template<>
struct DataType< ::gpio_control::gpio_statusRequest>
{
  static const char* value()
  {
    return DataType< ::gpio_control::gpio_status >::value();
  }
  static const char* value(const ::gpio_control::gpio_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gpio_control::gpio_statusResponse> should match
// service_traits::MD5Sum< ::gpio_control::gpio_status >
template<>
struct MD5Sum< ::gpio_control::gpio_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gpio_control::gpio_status >::value();
  }
  static const char* value(const ::gpio_control::gpio_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpio_control::gpio_statusResponse> should match
// service_traits::DataType< ::gpio_control::gpio_status >
template<>
struct DataType< ::gpio_control::gpio_statusResponse>
{
  static const char* value()
  {
    return DataType< ::gpio_control::gpio_status >::value();
  }
  static const char* value(const ::gpio_control::gpio_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPIO_CONTROL_MESSAGE_GPIO_STATUS_H
